### ISSUE TITLE
Kowalski Bible has some issues

### ISSUE THREAD

**Issue by Berovowilare** [rBiblia/bib2xml#2]
Hello the Kowalski Bible has some issues. 
Some verses are missing. For example Luke 1,26. You can see 1,25 ends with a full stop. And 1,27 starts lowercase. Some other verses are missing too.

Some verses are in the one before and after. They are not missing but simply combined in the one before or after. 

Thansk for the fixes.

**Comment by clash82** [comment]
@Berovowilare you are right!

Unfortunately, I don't have printed nor fixed digital version of this translation. Do you own one of them and could help me to fix it for rBiblia?

btw, sorry for late reply. You can use rBiblia's built-in tool to report issues like those, just press CTRL+E and write your message there (or use my contact form [here](https://kontakt.toborek.info)). It's not a good place here for topics like this.
